### ISSUE TITLE
Player isn't loading the video player like it should

### ISSUE THREAD

**Issue by cskiwi** [bjarnoldus/video-hls#4]
As one mentioned here:
https://github.com/bjarnoldus/momovi-video-hls/issues/1#issuecomment-53254590

I'm having the same issue: The player doesn't always load the UI when initializing / auto playing it, so sometimes the play button is still in the center, and the time control etc isn't shown.

**Comment by bjarnoldus** [comment]
Hi Glenn,

Is this only for the Flash player (non-safari browser). You need to install the crossdomain.xml correctly, including the right server configuration.

Jeroen

**Comment by cskiwi** [comment]
This is for the flash plugin, I'm trying HLS.

I've setup a crossdomain.xml with the following configuration:
and it still doesn't work. 

``` xml
<?xml version="1.0"?>
<!DOCTYPE cross-domain-policy 
  SYSTEM "http://www.macromedia.com/xml/dtds/cross-domain-policy.dtd">
<cross-domain-policy>
  <allow-access-from domain="*" />
</cross-domain-policy>
```
